WITH source AS (
    SELECT * FROM {{ source('nobs', 'stat_statistikk') }}
),

renamed AS (
    SELECT
        [__kplt__ID]                                       AS pk_statistikk_id,
        [_kflt_AvdelingID]                                 AS fk_avdeling_id,
        [_kflt_FakturaID]                                  AS fk_faktura_id,
        [_kflt_IngenioerID]                                AS fk_ingenioer_id,
        [_kflt_KundeID]                                    AS fk_kunde_id,
        [_kflt_OrdreID]                                    AS fk_ordre_id,
        [_kflt_OrdrehjelpemiddelID]                        AS fk_ordrehjelpemiddel_id,
        [_kflt_OrtokID]                                    AS fk_ortok_id,
        [_kflt_PasientID]                                  AS fk_pasient_id,
        [_kflt_Produksjonsansvarlig]                       AS fk_produksjonsansvarlig_id,
        [_kflt_Produksjonsstatus]                          AS fk_produksjonsstatus_id,
        [_kflt_RekvirentID]                                AS fk_rekvirent_id,
        [_kflt_StedID]                                     AS fk_sted_id,
        [OrdreNummer]                                      AS order_number,
        [Fakturanummer]                                    AS invoice_number,
        [Antall]                                           AS quantity,
        [Status_lct]                                       AS status,
        [Nomenklaturkode]                                  AS nomenclature_code,
        [HovedgruppeKode]                                  AS main_group_code,
        TRY_CAST([Dato_Ordredato] AS DATE)                 AS order_date,
        TRY_CAST([Dato_Levert] AS DATE)                    AS delivery_date,
        TRY_CAST([Dato_PlanlagtLevering] AS DATE)          AS planned_delivery_date,
        TRY_CAST([Dato_Faktura] AS DATE)                   AS invoice_date,
        TRY_CAST([Hasteordre] AS BIT)                      AS is_urgent,
        [Dager_Fremstillingstid]                           AS days_manufacturing,
        [Dager_Produksjon]                                 AS days_production,
        [Dager_Produksjonsopphold]                         AS days_production_hold,
        [FakturaSum]                                       AS invoice_total,
        [FakturaSumEksMva]                                 AS invoice_total_ex_vat,
        [Kost_Arbeid]                                      AS cost_labor,
        [Kost_Arbeid_Estimert]                             AS cost_labor_estimated,
        [Kost_Arbeid_Registrert]                           AS cost_labor_registered,
        [Kost_Fastpris]                                    AS cost_fixed_price,
        [Kost_Fastpris_Estimert]                           AS cost_fixed_price_estimated,
        [Kost_Faststoenad]                                 AS cost_fixed_allowance,
        [Kost_Faststoenad_Ink_EA_NAV]                      AS cost_fixed_allowance_incl_nav,
        [Kost_Faststoenad_Eks_EA_NAV]                      AS cost_fixed_allowance_excl_nav,
        [Kost_Materialer]                                  AS cost_materials,
        [Kost_Materialer_Estimert]                         AS cost_materials_estimated,
        [Kost_Materialer_Registrert]                       AS cost_materials_registered,
        [Kost_Total]                                       AS cost_total,
        [Kost_Total_Estimert]                              AS cost_total_estimated,
        [Kost_Total_Registrert]                            AS cost_total_registered,
        [EB_Egenbetaling]                                  AS copay_amount,
        [EB_EgenbetalingType]                              AS copay_type,
        [EB_Egenbetaling_Dekket_NAV]                       AS copay_covered_nav,
        [EB_Egenbetaling_Dekket_Pasient]                   AS copay_covered_patient,
        [Tid_Timeantall1]                                  AS hours_registered_1,
        [Tid_Timeantall2]                                  AS hours_registered_2,
        [Tid_Timeantall_Estimert]                          AS hours_estimated,
        [Tid_Timeantall_Fast]                              AS hours_fixed,
        [Tid_Registrert_Timeantall1]                       AS hours_registered_timecount1,
        [Tid_Registrert_001]                               AS hours_registered_001,
        [Tid_Registrert_002]                               AS hours_registered_002,
        [Tid_Registrert_003]                               AS hours_registered_003,
        [Tid_Timeantall1_inklFastPris]                     AS hours_incl_fixed_price,
        [Timepris01]                                       AS hourly_rate,
        [Pas_Pasientnr]                                    AS patient_number,
        [Pas_Foedselsaar]                                  AS patient_birth_year,
        [Pas_Kjoenn]                                       AS patient_gender,
        [Avdeling_lct]                                     AS department,
        [Sted_lct]                                         AS location,
        [Sted_Fylke]                                       AS county,
        [Sted_Kommune]                                     AS municipality,
        [Sted_Postnr]                                      AS postal_code,
        [Sted_Poststed]                                    AS postal_place,
        [NAVKontor_Nummer]                                 AS nav_office_number,
        [Klinisk_AarsakBehov]                              AS clinical_reason,
        [Klinisk_ICD10]                                    AS clinical_icd10,
        [Fagomraade_lct]                                   AS specialty_area,
        [_kalt_Fagomraade]                                 AS calc_specialty_code,
        [_kalt_FakturaType]                                AS calc_invoice_type,
        [_kalt_Fakturert]                                  AS calc_is_invoiced,
        [_kalt_KundeKategori]                              AS calc_customer_category,
        [_kalt_NomenklaturType]                            AS calc_nomenclature_type,
        [_kalt_OrdreType]                                  AS calc_order_type,
        TRY_CAST([zz__AnnulertFlag] AS INT)                AS is_cancelled,
        TRY_CAST([zz__FakturertFlag] AS INT)               AS is_invoiced,
        TRY_CAST([zz__IProduksjonFlag] AS INT)             AS is_in_production,
        TRY_CAST([zz__TilFaktureringFlag] AS INT)          AS is_ready_for_invoicing,
        TRY_CAST([zz__IsDeleted] AS INT)                   AS is_deleted,
        TRY_CAST([zz__Creation_Timestamp__lxm] AS DATETIME2(6)) AS created_at,
        [zz__Creation_AccountName__lxt]                    AS created_by,
        TRY_CAST([zz__Modification_Timestamp__lxm] AS DATETIME2(6)) AS modified_at,
        [zz__Modification_AccountName__lxt]                AS modified_by,
        TRY_CAST([_ingestion_timestamp] AS DATETIME2(6))      AS ingested_at
    FROM source
)

SELECT *
FROM renamed
WHERE is_deleted = 0 OR is_deleted IS NULL
