WITH source AS (
    SELECT * FROM {{ source('nobs', 'statkliniker') }}
),

renamed AS (
    SELECT
        [__kplt__ID]                                       AS pk_kliniker_id,
        [_kflt_AvdelingID]                                 AS fk_avdeling_id,
        [_kflt_PersonID]                                   AS fk_person_id,
        [BrukerID]                                         AS user_id,
        [Medarbeider_Visningsnavn_lct]                     AS employee_display_name,
        [Medarbeider_RessursType_lct]                      AS employee_resource_type,
        [Avdelingsnavn_lct]                                AS department_name,
        [Nomenklatur]                                      AS nomenclature,
        [AntallAvtaler_HittilIAar]                         AS count_appointments_ytd,
        [AntallAvtaler_ForrigeMnd]                         AS count_appointments_prev_month,
        [AntallAvtaler_Forrige3Mnd]                        AS count_appointments_prev_3_months,
        [AntallAvtaler_Forrige6Mnd]                        AS count_appointments_prev_6_months,
        [AntallAvtaler_ForrigeUke]                         AS count_appointments_prev_week,
        [Antall_Kommende1Mnd]                              AS count_appointments_next_1_month,
        [AntallAvtaler_Kommende2Mnd]                       AS count_appointments_next_2_months,
        [AntallAvtaler_Kommende3Mnd]                       AS count_appointments_next_3_months,
        [Antall_ordre]                                     AS count_orders,
        [Antall_ordre_typeK]                               AS count_orders_type_k,
        [Fak_Antall_ordre]                                 AS count_orders_invoiced,
        [Fak_Antall_ordre_typeK]                           AS count_orders_invoiced_type_k,
        [VarighetAvtaler_HittilIAar]                       AS duration_appointments_ytd,
        [VarighetAvtaler_ForrigeMnd]                       AS duration_appointments_prev_month,
        [VarighetAvtaler_Forrige3Mnd]                      AS duration_appointments_prev_3_months,
        [VarighetAvtaler_Forrige6Mnd]                      AS duration_appointments_prev_6_months,
        [VarighetAvtaler_ForrigeUke]                       AS duration_appointments_prev_week,
        [VarighetAvtaler_Kommende1Mnd]                     AS duration_appointments_next_1_month,
        [VarighetAvtaler_Kommende2Mnd]                     AS duration_appointments_next_2_months,
        [VarighetAvtaler_Kommende3Mnd]                     AS duration_appointments_next_3_months,
        [VarighetAvtaler_GjSnitt_HittilIAar]               AS duration_avg_ytd,
        [VarighetAvtaler_GjSnitt_ForrigeMnd]               AS duration_avg_prev_month,
        [VarighetAvtaler_GjSnitt_ForrigeUke]               AS duration_avg_prev_week,
        [VarighetAvtaler_GjSnitt_Kommende3Mnd]             AS duration_avg_next_3_months,
        [VarighetAvtaler_MAX_HittilIAar]                   AS duration_max_ytd,
        [VarighetAvtaler_MAX_ForrigeMnd]                   AS duration_max_prev_month,
        [VarighetAvtaler_MAX_ForrigeUke]                   AS duration_max_prev_week,
        [VarighetAvtaler_MAX_Kommende3Mnd]                 AS duration_max_next_3_months,
        [VarighetAvtaler_MIN_HittilIAar]                   AS duration_min_ytd,
        [VarighetAvtaler_MIN_ForrigeMnd]                   AS duration_min_prev_month,
        [VarighetAvtaler_MIN_ForrigeUke]                   AS duration_min_prev_week,
        [VarighetAvtaler_MIN_Kommende3Mnd]                 AS duration_min_next_3_months,
        [Sum_Total]                                        AS sum_total,
        [Sum_Total_NAV]                                    AS sum_total_nav,
        [Sum_FastPris]                                     AS sum_fixed_price,
        [Sum_FastPris_typeK]                               AS sum_fixed_price_type_k,
        [Sum_FastStoenad]                                  AS sum_fixed_allowance,
        [Sum_FastTid]                                      AS sum_fixed_time,
        [Sum_TidVerdi]                                     AS sum_time_value,
        [Sum_TidVerdi_lcn]                                 AS sum_time_value_local,
        [SumFak_Total]                                     AS sum_invoiced_total,
        [SumFak_Total_NAV]                                 AS sum_invoiced_total_nav,
        [SumFak_FakturertTid]                              AS sum_invoiced_time,
        [SumFak_FastPris]                                  AS sum_invoiced_fixed_price,
        [SumFak_FastPris_typeK]                            AS sum_invoiced_fixed_price_type_k,
        [SumFak_FastStoenad]                               AS sum_invoiced_fixed_allowance,
        [SumFak_FastTid]                                   AS sum_invoiced_fixed_time,
        [SumFak_TidVerdi]                                  AS sum_invoiced_time_value,
        [SumFak_TidVerdi_lcn]                              AS sum_invoiced_time_value_local,
        [Sum_EstimertTid]                                  AS sum_estimated_time,
        [Sum_EstimertTid_Dag]                              AS sum_estimated_time_day,
        [Sum_EstimertTid_Uke]                              AS sum_estimated_time_week,
        [Sum_EstimertTid_Maaned]                           AS sum_estimated_time_month,
        [Sum_EstimertTid_K]                                AS sum_estimated_time_k,
        [Sum_EstimertTid_N]                                AS sum_estimated_time_n,
        [Sum_EstimertTid_R]                                AS sum_estimated_time_r,
        [Budsjett_Timer]                                   AS budget_hours,
        [Budsjett_Timer_Produsert]                         AS budget_hours_produced,
        [Timer]                                            AS hours_total,
        [Timer_I]                                          AS hours_category_i,
        [Timer_K]                                          AS hours_category_k,
        [Timer_N]                                          AS hours_category_n,
        [Timer_R]                                          AS hours_category_r,
        [Utvikling_Total]                                  AS trend_total,
        [Utvikling_Sum_Total_NAV]                          AS trend_total_nav,
        [Utvikling_TidVerdi]                               AS trend_time_value,
        [Utvikling_FastPris]                               AS trend_fixed_price,
        [Utvikling_FastPris_typeK]                         AS trend_fixed_price_type_k,
        [Utvikling_FastStoenad]                            AS trend_fixed_allowance,
        [Utvikling_FastTid]                                AS trend_fixed_time,
        [Utvikling_EstimertTid]                            AS trend_estimated_time,
        [Utvikling_Antall_ordre]                           AS trend_order_count,
        [Utvikling_Antall_ordre_typeK]                     AS trend_order_count_type_k,
        [Utvikling_SumFak_Total]                           AS trend_invoiced_total,
        [Utvikling_SumFak_Total_NAV]                       AS trend_invoiced_total_nav,
        [Utvikling_SumFak_TidVerdi]                        AS trend_invoiced_time_value,
        [Utvikling_SumFak_FakturertTid]                    AS trend_invoiced_time,
        [Utvikling_SumFak_FastPris]                        AS trend_invoiced_fixed_price,
        [Utvikling_SumFak_FastPris_typeK]                  AS trend_invoiced_fixed_price_type_k,
        [Utvikling_SumFak_FastStoenad]                     AS trend_invoiced_fixed_allowance,
        [Utvikling_SumFak_FastTid]                         AS trend_invoiced_fixed_time,
        [Utvikling_Fak_Antall_ordre]                       AS trend_invoiced_order_count,
        [Utvikling_Fak_Antall_ordre_typeK]                 AS trend_invoiced_order_count_type_k,
        TRY_CAST([Dato_fom] AS DATE)                       AS report_date_from,
        TRY_CAST([Dato_tom] AS DATE)                       AS report_date_to,
        TRY_CAST([Dato__Prev_fom] AS DATE)                 AS report_prev_date_from,
        TRY_CAST([Dato__Prev_tom] AS DATE)                 AS report_prev_date_to,
        TRY_CAST([Dato__DetteAarStart] AS DATE)            AS date_this_year_start,
        TRY_CAST([Dato__HittilIAarSlutt] AS DATE)          AS date_ytd_end,
        TRY_CAST([Dato__ForrigeMndStart] AS DATE)          AS date_prev_month_start,
        TRY_CAST([Dato__ForrigeMndSlutt] AS DATE)          AS date_prev_month_end,
        TRY_CAST([Dato__Forrige3MndStart] AS DATE)         AS date_prev_3_months_start,
        TRY_CAST([Dato__Forrige6MndStart] AS DATE)         AS date_prev_6_months_start,
        TRY_CAST([Dato__ForrigeUkeStart] AS DATE)          AS date_prev_week_start,
        TRY_CAST([Dato__ForrigeUkeSlutt] AS DATE)          AS date_prev_week_end,
        TRY_CAST([Dato__KommendeMndStart] AS DATE)         AS date_next_month_start,
        TRY_CAST([Dato__Kommende1MndSlutt] AS DATE)        AS date_next_1_month_end,
        TRY_CAST([Dato__Kommende2MndSlutt] AS DATE)        AS date_next_2_months_end,
        TRY_CAST([Dato__Kommende3MndSlutt] AS DATE)        AS date_next_3_months_end,
        [_kalt_Fag]                                        AS calc_subject,
        [_kalt_Fag_Hoved]                                  AS calc_main_subject,
        [_kalt_ResourceType]                               AS calc_resource_type,
        [_kalt_Type]                                       AS calc_type,
        TRY_CAST([zz__IsActive] AS INT)                    AS is_active,
        TRY_CAST([zz__IsDeleted] AS INT)                   AS is_deleted,
        TRY_CAST([zz__IsLocked] AS INT)                    AS is_locked,
        TRY_CAST([zz__Creation_Timestamp__lxm] AS DATETIME2) AS created_at,
        [zz__Creation_AccountName__lxt]                    AS created_by,
        TRY_CAST([zz__Modification_Timestamp__lxm] AS DATETIME2) AS modified_at,
        [zz__Modification_AccountName__lxt]                AS modified_by,
        TRY_CAST([_ingestion_timestamp] AS DATETIME2)      AS ingested_at
    FROM source
)

SELECT *
FROM renamed
WHERE is_deleted = 0 OR is_deleted IS NULL
