CREATE TABLE [core].[core_ops__patient] (
    [pk_patient_id]                       VARCHAR (8000) NULL,
    [patient_number]                      VARCHAR (8000) NULL,
    [first_name]                          VARCHAR (8000) NULL,
    [last_name]                           VARCHAR (8000) NULL,
    [full_name]                           VARCHAR (8000) NULL,
    [national_id_number]                  VARCHAR (8000) NULL,
    [birth_date]                          DATE           NULL,
    [birth_year]                          BIGINT         NULL,
    [approximate_age]                     BIGINT         NULL,
    [gender]                              VARCHAR (8000) NULL,
    [patient_status]                      VARCHAR (8000) NULL,
    [patient_status_code]                 VARCHAR (8000) NULL,
    [patient_type]                        VARCHAR (8000) NULL,
    [is_address_secret]                   VARCHAR (8000) NULL,
    [address_line_1]                      VARCHAR (8000) NULL,
    [address_line_2]                      VARCHAR (8000) NULL,
    [postal_code]                         VARCHAR (8000) NULL,
    [city]                                VARCHAR (8000) NULL,
    [country]                             VARCHAR (8000) NULL,
    [municipality]                        VARCHAR (8000) NULL,
    [municipality_code]                   VARCHAR (8000) NULL,
    [county]                              VARCHAR (8000) NULL,
    [department_name]                     VARCHAR (8000) NULL,
    [meeting_place]                       VARCHAR (8000) NULL,
    [institution]                         VARCHAR (8000) NULL,
    [nav_customer_number]                 VARCHAR (8000) NULL,
    [fk_health_personnel_fastlege]        VARCHAR (8000) NULL,
    [fk_health_personnel_henvisende_lege] VARCHAR (8000) NULL,
    [fk_health_personnel_rekvirent]       VARCHAR (8000) NULL,
    [fk_health_personnel_fysioterapeut]   VARCHAR (8000) NULL,
    [fk_health_personnel_ergoterapeut]    VARCHAR (8000) NULL,
    [fk_employee_ortopediingenior]        VARCHAR (8000) NULL,
    [fk_avdeling_id]                      VARCHAR (8000) NULL,
    [fk_sted_id]                          VARCHAR (8000) NULL,
    [recall_interval]                     VARCHAR (8000) NULL,
    [recall_next]                         VARCHAR (8000) NULL,
    [recall_next_location]                VARCHAR (8000) NULL,
    [recall_duration_hours]               FLOAT (53)     NULL,
    [recall_opbh_interval]                VARCHAR (8000) NULL,
    [recall_opbh_next]                    VARCHAR (8000) NULL,
    [recall_time_preference]              VARCHAR (8000) NULL,
    [recall_last_followup_date]           DATE           NULL,
    [bank_account_number]                 VARCHAR (8000) NULL,
    [reminders]                           VARCHAR (8000) NULL,
    [has_extended_profile]                INT            NOT NULL,
    [date_created_business]               DATE           NULL,
    [created_at]                          DATETIME2 (6)  NULL,
    [modified_at]                         DATETIME2 (6)  NULL
);


GO