CREATE TABLE [core].[core_ops__order_line] (
    [pk_order_line_id]           VARCHAR (8000) NULL,
    [fk_order]                   VARCHAR (8000) NULL,
    [parent_order_line_id]       VARCHAR (8000) NULL,
    [component_id]               VARCHAR (8000) NULL,
    [supplier_id]                VARCHAR (8000) NULL,
    [fk_avdeling_id]             VARCHAR (8000) NULL,
    [fk_sted_id]                 VARCHAR (8000) NULL,
    [order_number]               VARCHAR (8000) NULL,
    [line_status]                VARCHAR (8000) NULL,
    [production_status]          VARCHAR (8000) NULL,
    [nomenclature_code]          VARCHAR (8000) NULL,
    [destination_code]           VARCHAR (8000) NULL,
    [quantity_ordered]           FLOAT (53)     NULL,
    [quantity_picked]            FLOAT (53)     NULL,
    [article_number_internal]    VARCHAR (8000) NULL,
    [article_number_supplier]    VARCHAR (8000) NULL,
    [article_name_internal]      VARCHAR (8000) NULL,
    [article_name_supplier]      VARCHAR (8000) NULL,
    [supplier_number]            VARCHAR (8000) NULL,
    [supplier_admin_number]      VARCHAR (8000) NULL,
    [supplier_name]              VARCHAR (8000) NULL,
    [unit_price]                 FLOAT (53)     NULL,
    [unit_price_in]              FLOAT (53)     NULL,
    [unit_price_out]             FLOAT (53)     NULL,
    [line_amount]                FLOAT (53)     NULL,
    [line_amount_picked_in]      FLOAT (53)     NULL,
    [line_amount_picked_out]     FLOAT (53)     NULL,
    [invoice_number]             VARCHAR (8000) NULL,
    [copay_invoice_number]       VARCHAR (8000) NULL,
    [order_date]                 DATE           NULL,
    [registered_date]            DATE           NULL,
    [ordered_from_supplier_date] DATE           NULL,
    [picked_date]                DATE           NULL,
    [invoice_date]               DATE           NULL,
    [copay_invoice_date]         DATE           NULL,
    [department_name]            VARCHAR (8000) NULL,
    [location_name]              VARCHAR (8000) NULL,
    [is_locked]                  INT            NULL,
    [created_at]                 DATETIME2 (6)  NULL,
    [created_by]                 VARCHAR (8000) NULL,
    [modified_at]                DATETIME2 (6)  NULL,
    [modified_by]                VARCHAR (8000) NULL
);


GO